
.ifndef ::__VRAM_H_
::__VRAM_H_ = 1

.include "includes/registers.inc"

;; VRAM Map
;; WORD ADDRESSES
PPU_PIPEGAME_SCREEN_MODE	= BGMODE_MODE1

PPU_PIPEGAME_BG1_MAP		= $0000
PPU_PIPEGAME_BG2_MAP		= $0400
PPU_PIPEGAME_BG3_MAP		= $0800
PPU_PIPEGAME_BG1_TILES		= $1000
PPU_PIPEGAME_BG2_TILES		= $2000
PPU_PIPEGAME_BG3_TILES		= $5000
PPU_PIPEGAME_OAM_TILES		= $6000

PPU_PIPEGAME_BG1_SIZE		= BGXSC_SIZE_32X32
PPU_PIPEGAME_BG2_SIZE		= BGXSC_SIZE_32X32
PPU_PIPEGAME_BG3_SIZE		= BGXSC_SIZE_32X32

PPU_PIPEGAME_OAM_SIZE		= OBSEL_SIZE_8_16
PPU_PIPEGAME_OAM_NAME		= 0

; Pipes in front of background:
PPU_PIPEGAME_PIPES_TILES	= PPU_PIPEGAME_BG1_TILES
PPU_PIPEGAME_BACKGROUND_TILES	= PPU_PIPEGAME_BG2_TILES
PPU_PIPEGAME_PIPES_MAP		= PPU_PIPEGAME_BG1_MAP
PPU_PIPEGAME_BACKGROUND_MAP	= PPU_PIPEGAME_BG2_MAP

.endif ; __VRAM_H_

; vim: ft=asm:

